### PR TITLE
Spelling corrections

### PR DESCRIPTION
**Pull request by jubalh**

### CODE REVIEW

**Comment by stefanberger** [comment]
Can you please add a Signed-off-by line to each one of your patches? Otherwise they look good to me. Thank you!

**Comment by lumjjb** [comment]
You can use `git commit --amend --signoff` but since you have two commits, you may need to squash them first (https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc)

**Comment by jubalh** [comment]
Thanks for the feedback! I signed the commits off now.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
