### PR TITLE
gh: move files inside `.github/` dir

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
This PR aims to move the `SECURITY.md` and `CODE_OF_CONDUCT.md` file from the root of the directory to the `.github/` directory. Github looks for a contribution guideline file in the following order: `.github dir > project root > docs dir` ([source](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)). Moving the files to the `.github/` dir leads to a minimal project structure without any functional change.

### CODE REVIEW

**Comment by stefanberger** [comment]
I looked around on the other projects of github.com/containers and they all have it in their root directory. Are you going to change it for these as well?

**Comment by SauravMaheshkar** [comment]
> I looked around on the other projects of github.com/containers and they all have it in their root directory. Are you going to change it for these as well?

Yes, I'm more than happy to make PRs in other repositories within the `containers` namespace 😄

**Comment by stefanberger** [comment]
> I'm assuming the first one should be the [**containers/common**](https://github.com/containers/common) repository

It's your choice. I think these files should remain visible right in the root directory.

**Comment by SauravMaheshkar** [comment]
> > I'm assuming the first one should be the [**containers/common**](https://github.com/containers/common) repository
> 
> It's your choice. I think these files should remain visible right in the root directory.

In that case, I think I'll raise a issue in [**containers/common**](https://github.com/containers/common) and then depending on the response follow up/close this PR.

**Pull request closed without merging**
